### ISSUE TITLE
关于Java版本

### ISSUE THREAD

**Issue by biaobiaoqi** [soulmachine/leetcode#16]
您好，Java目录下没有内容，是还没有来得做么？
我最近正在使用您总结的教材来刷题，我是用Java的，可以正好补充Java的版本。

**Comment by Gabriel-18** [comment]
> 好的。
> 给我大概一个月的时间=)

老哥你的代码呢...

**Comment by JerryQiang** [comment]
所以现在Java版本的代码是已经有了，还没有merge嘛？
还是其他什么情况？

**Comment by soulmachine** [comment]
@JerryQiang Java代码已有，没有 Merge, 在这里 https://algorithm-essentials.soulmachine.me/  。目前没有精力做这个了
