### ISSUE TITLE
仓主现在是不打算继续更新了吗？

### ISSUE THREAD

**Issue by zhaoweiwang** [soulmachine/leetcode#74]
觉得很可惜，这个题解很受用，希望可以继续更下去

**Comment by Byelaney** [comment]
会更的，最近比较忙，在国外求学，没想到有人看

從我的 iPhone 傳送

**Comment by gaoryrt** [comment]
有人看的，仓主加油

**Comment by soulmachine** [comment]
我决定继续维护，更新，欢迎大家围观 :D

**Comment by Byelaney** [comment]
Take the world's best courses, online. Coursera envisions a world where 
anyone, anywhere can transform their life by accessing the world’s best 
learning experience.
[Ready to learn something new?]
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLmwwbEdfLXNrRWVXZnBRcGRhNjhkTnciLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDc0ZWRlMWZlNDI4OGZjZjQ2ZThlZjY1YTVhM2VhODRiNmY0YzYyNzYzY2QyOGU5MmNmMDAwMDAwMDExMjIzMGIxYzkyYTE2OWNlMDY3ZjNmNGVAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8ubDBsR18tc2tFZVdmcFFwZGE2OGROdyJ9fSwidXNlcklkIjotMX0.ZrM5_RrWjz2gjH4PucDFjRiD3MiAtNa9yZy2w2zhFLM> 	
My Courses
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLmwwbEdfLXNrRWVXZnBRcGRhNjhkTnciLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDc0ZWRlMWZlNDI4OGZjZjQ2ZThlZjY1YTVhM2VhODRiNmY0YzYyNzYzY2QyOGU5MmNmMDAwMDAwMDExMjIzMGIxYzkyYTE2OWNlMDY3ZjNmNGVAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8ubDBsR18tc2tFZVdmcFFwZGE2OGROdyJ9fSwidXNlcklkIjotMX0.ZrM5_RrWjz2gjH4PucDFjRiD3MiAtNa9yZy2w2zhFLM> 
Course Catalog
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvY291cnNlcz91dG1fbWVkaXVtPWVtYWlsJnV0bV9zb3VyY2U9aW52aXRhdGlvbnMmdXRtX2NhbXBhaWduPW5vdGlmaWNhdGlvbnMuYXV0by5sMGxHXy1za0VlV2ZwUXBkYTY4ZE53IiwidHJhY2tpbmciOnsidXNlcklkIjotMSwidXNlckVtYWlsIjoicmVwbHkrMDA3NGVkZTFmZTQyODhmY2Y0NmU4ZWY2NWE1YTNlYTg0YjZmNGM2Mjc2M2NkMjhlOTJjZjAwMDAwMDAxMTIyMzBiMWM5MmExNjljZTA2N2YzZjRlQHJlcGx5LmdpdGh1Yi5jb20iLCJub3RpZmljYXRpb25UeXBlIjoiZ3Jvd3RoLmludml0YXRpb24iLCJjYW1wYWlnbklkIjoibm90aWZpY2F0aW9ucy5hdXRvLmwwbEdfLXNrRWVXZnBRcGRhNjhkTncifX0sInVzZXJJZCI6LTF9.GFTOhjhJKLdmkTdIJJR2Vl90HZdl4AUPLjByEi3bkZA>


Hal thinks you'll love learning on Coursera

We envision a world where anyone, anywhere can transform their life by 
accessing the world’s best learning experience. We offer hundreds open 
online courses, in dozens of subject areas, all from top universities and 
institutions.

Course topics range from business and management, to computer science, to 
medicine, music, education, and more.

Millions of our learners have advanced their careers, discovered new 
passions, and built lasting friendships through their Coursera courses. We 
hope you'll join us in learning without limits!

The Coursera Team

Explore Coursera
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvb25ib2FyZGluZy8_dG9rZW49YTlmM2JjMDg2MTI5YjdmN2Q1ZTYzNGUxMTY0MGVkMmYmZW1haWw9cmVwbHkrMDA3NGVkZTFmZTQyODhmY2Y0NmU4ZWY2NWE1YTNlYTg0YjZmNGM2Mjc2M2NkMjhlOTJjZjAwMDAwMDAxMTIyMzBiMWM5MmExNjljZTA2N2YzZjRlQHJlcGx5LmdpdGh1Yi5jb20mbmFtZT1zb3VsbWFjaGluZS9sZWV0Y29kZT91dG1fbWVkaXVtPWVtYWlsJnV0bV9zb3VyY2U9aW52aXRhdGlvbnMmdXRtX2NhbXBhaWduPW5vdGlmaWNhdGlvbnMuYXV0by5sMGxHXy1za0VlV2ZwUXBkYTY4ZE53IiwidHJhY2tpbmciOnsidXNlcklkIjotMSwidXNlckVtYWlsIjoicmVwbHkrMDA3NGVkZTFmZTQyODhmY2Y0NmU4ZWY2NWE1YTNlYTg0YjZmNGM2Mjc2M2NkMjhlOTJjZjAwMDAwMDAxMTIyMzBiMWM5MmExNjljZTA2N2YzZjRlQHJlcGx5LmdpdGh1Yi5jb20iLCJub3RpZmljYXRpb25UeXBlIjoiZ3Jvd3RoLmludml0YXRpb24iLCJjYW1wYWlnbklkIjoibm90aWZpY2F0aW9ucy5hdXRvLmwwbEdfLXNrRWVXZnBRcGRhNjhkTncifX0sInVzZXJJZCI6LTF9.krP4s_H3gbjkoiD0VDonAfwKRRYPVMH1uVH25tOFQGg>
Download our App:  iOS
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL2l0dW5lcy5hcHBsZS5jb20vYXBwL2FwcGxlLXN0b3JlL2lkNzM2NTM1OTYxP2N0PU1vYmlsZSUyMFByb21vJTIwRW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZtdD04JnB0PTIzMzQxNTAmdXRtX2NhbXBhaWduPW5vdGlmaWNhdGlvbnMuYXV0by5sMGxHXy1za0VlV2ZwUXBkYTY4ZE53JnV0bV9tZWRpdW09ZW1haWwiLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDc0ZWRlMWZlNDI4OGZjZjQ2ZThlZjY1YTVhM2VhODRiNmY0YzYyNzYzY2QyOGU5MmNmMDAwMDAwMDExMjIzMGIxYzkyYTE2OWNlMDY3ZjNmNGVAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8ubDBsR18tc2tFZVdmcFFwZGE2OGROdyJ9fSwidXNlcklkIjotMX0.WXac3bVj0Hcx1VyFp1rsz1jvlT8euhfL78EFm-WuTzc> 
  |  Android
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3BsYXkuZ29vZ2xlLmNvbS9zdG9yZS9hcHBzL2RldGFpbHM_aWQ9b3JnLmNvdXJzZXJhLmFuZHJvaWQmdXRtX21lZGl1bT1lbWFpbCZ1dG1fc291cmNlPWludml0YXRpb25zJnV0bV9jYW1wYWlnbj1ub3RpZmljYXRpb25zLmF1dG8ubDBsR18tc2tFZVdmcFFwZGE2OGROdyIsInRyYWNraW5nIjp7InVzZXJJZCI6LTEsInVzZXJFbWFpbCI6InJlcGx5KzAwNzRlZGUxZmU0Mjg4ZmNmNDZlOGVmNjVhNWEzZWE4NGI2ZjRjNjI3NjNjZDI4ZTkyY2YwMDAwMDAwMTEyMjMwYjFjOTJhMTY5Y2UwNjdmM2Y0ZUByZXBseS5naXRodWIuY29tIiwibm90aWZpY2F0aW9uVHlwZSI6Imdyb3d0aC5pbnZpdGF0aW9uIiwiY2FtcGFpZ25JZCI6Im5vdGlmaWNhdGlvbnMuYXV0by5sMGxHXy1za0VlV2ZwUXBkYTY4ZE53In19LCJ1c2VySWQiOi0xfQ.udqZpkjDigcswr_I9CAZkJw3cijJJnnGYCElhFLwStI>
Learner Help Center
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL2xlYXJuZXIuY291cnNlcmEuaGVscC8_dXRtX21lZGl1bT1lbWFpbCZ1dG1fc291cmNlPWludml0YXRpb25zJnV0bV9jYW1wYWlnbj1ub3RpZmljYXRpb25zLmF1dG8ubDBsR18tc2tFZVdmcFFwZGE2OGROdyIsInRyYWNraW5nIjp7InVzZXJJZCI6LTEsInVzZXJFbWFpbCI6InJlcGx5KzAwNzRlZGUxZmU0Mjg4ZmNmNDZlOGVmNjVhNWEzZWE4NGI2ZjRjNjI3NjNjZDI4ZTkyY2YwMDAwMDAwMTEyMjMwYjFjOTJhMTY5Y2UwNjdmM2Y0ZUByZXBseS5naXRodWIuY29tIiwibm90aWZpY2F0aW9uVHlwZSI6Imdyb3d0aC5pbnZpdGF0aW9uIiwiY2FtcGFpZ25JZCI6Im5vdGlmaWNhdGlvbnMuYXV0by5sMGxHXy1za0VlV2ZwUXBkYTY4ZE53In19LCJ1c2VySWQiOi0xfQ.iNIsZSDTI_vrsfCntynOyS-eVZMdXlpN6smypMvxuNE> 
  | Please do not reply directly to this email
To no longer receive invitations from your friends on Coursera, 
Unsubscribe
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvYWNjb3VudC91bnN1YnNjcmliZS92alhJVkZtNXpMSlJaZDV2dWNoTDRmZTVWSFNEaW4ycGU4eUVra3FqVmVabF9DYm85TV9felBtTzZiWjJtVGl6eHo4Yzl0Qm55UGY4eDAzY0hHMFg4Zy5Ed0lZV19zRWttTnVXRDRFbWJiU2dnLk9UYTNzdWdjbFZRR2xkUi01Q0QtV3lrQTJfcUpiOUZDcFdfRTRtQzBRQ0lkdFozQWFhd214emtIZEFLMEhGN3djdWtGVjNNcFJwRGp2SEZKNGlxaGI1bDNmVXpOWUI3ckNjZDJzS015RXlmR280XzhzTlBlbVdVYkNSeUZSLUhwWFFXcjJ1Q2N0VUlyYVkxQ0xaMmwwQkU1bjA5aV9YaEFNelIyNUw5Qm54akM3ZFlmZ2E1bGRmOW1LbXUyUWFfSjUzUVRCYzdXUENmRE1FY2d5VVZVS19uNUtObTBFSXU5UHEwdHgxSFRrQ29USGtybGN3UmVORWRXekRLd0Uwc3ZlQk42XzAxSU82Q3EwUEh3TU91cS02VlF6NlV1Z250OXlGTkFQbzhPMHZNP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLmwwbEdfLXNrRWVXZnBRcGRhNjhkTnciLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDc0ZWRlMWZlNDI4OGZjZjQ2ZThlZjY1YTVhM2VhODRiNmY0YzYyNzYzY2QyOGU5MmNmMDAwMDAwMDExMjIzMGIxYzkyYTE2OWNlMDY3ZjNmNGVAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8ubDBsR18tc2tFZVdmcFFwZGE2OGROdyJ9fSwidXNlcklkIjotMX0.1_23g9S5VXmFOAakOPNcKj8_ggi5Cj7byh_i23by63I>
Copyright © 2016, Coursera Inc. | 381 E. Evelyn Ave, Mountain View, CA 
94041 USA
