### ISSUE TITLE
仓主不理这个仓库了？

### ISSUE THREAD

**Issue by zhaoweiwang** [soulmachine/leetcode#75]
RT

**Comment by soulmachine** [comment]
恩，这个确定会停止更新了，以后的更新都在这个repo , [LintCode题解](https://github.com/soulmachine/lintcode)

**Comment by Yanonankai** [comment]
LeetCode和LintCode下都没有Java吧，只有C++？

**Comment by zhaoweiwang** [comment]
没有java，C++ 11看得实在是爽

**Comment by soulmachine** [comment]
这个 Repo 我决定继续维护
